version: '3'
services:
  web:
    build: './docker/php'
    container_name: rtask_php
    depends_on:
      - db
    volumes:
      - ./exercise:/var/www/rtask/web/modules/custom/exercise:cached
    links:
      - db
    ports:
      - "80:80"
  db:
    image: mysql:8.0-debian
    container_name: rtask_db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ZT9WDMf6pKjxNes
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: g9ZNMR1vRGfaiyX
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: rtask_pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ZT9WDMf6pKjxNes
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    links:
      - db
    ports:
     - "8001:80"
