<?php

/**
 * @file
 * Exercise module, defines:
 *   - ArticleBundle class
 *   - single REST endpoint for retrieving ArticleBundle nodes.
 */

/**
 * Implements hook_entity_bundle_info_alter().
 */
function exercise_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['article'])) {
    $bundles['node']['article']['class'] = \Drupal\exercise\Entity\Bundle\ArticleBundle::class;
  }
}
